#!/bin/bash

# This is a simple terminal alarm clock

MUSIC_DIR=~/Music/*

if [ -z $1 ]; then
    echo 'First parameter needs to give wait time in minutes'
    exit 0
fi

MINUTES=$1

START_TIME=$(date '+%s')o
END_TIME=$(date '+%s' -d "+ $MINUTES minutes")

while true; do
    sec_remaining=$((END_TIME - $(date '+%s')))
    echo -ne "\r\033[K"$((sec_remaining / 60))m $((sec_remaining % 60))s to activation
    [[ "$sec_remaining" -le 0 ]] && break
    sleep 1
done

mplayer -shuffle $MUSIC_DIR
exit 0
