#!/usr/bin/env python3

import os
import random

assisting_urls = [
    # Blue Star
    "https://www.youtube.com/watch?v=xSnuVnOZd1U&ist=PLarKqD2Ythc4u-nAHVRnmC6YH36rMm-qw&index=26",
    # Lucy Orb
    "https://youtu.be/AufydOsiD6M?t=13"
    # Puzzle (ending)
    "https://youtu.be/hA6iBjxqDro?t=196"
]

vid = random.choice(assisting_urls)

os.system(f"xdg-open {vid}")
