#!/home/johannes/miniconda3/bin/python

import json
from pathlib import Path
import argparse

parser = argparse.ArgumentParser(description='Extract subtitle spans from json file')
parser.add_argument('path', type=Path, help='path to whisper generated json subtitle file')
args = parser.parse_args()

if args.path.suffix != '.json':
    raise ValueError('Not a json file')

data = json.load(args.path.open())
for segment in data['segments']:
    print(f"{segment['start']}s,{segment['end']}s ", end='')
