#!/usr/bin/env python3

import time
import os
import subprocess
from datetime import datetime as dt, timedelta

notification_interval = timedelta(hours=2)

def bedtime():
    return dt.now().replace(hour=21, minute=0, second=0, microsecond=0)

next_notification_time = dt.now().replace(hour=0, minute=0, second=0, microsecond=0)
while next_notification_time <= dt.now() - notification_interval:
    next_notification_time += notification_interval

BED_TIME = bedtime() 
while True:
    print(dt.now(), "<>", next_notification_time)
    if next_notification_time <= dt.now():
        next_notification_time += notification_interval
        name = os.path.basename(__file__)
        time_till_bed = BED_TIME - dt.now()
        subprocess.run(["terminal-notifier", 
            "-title", "Reflect now", 
            "-message", f"It's {dt.now().strftime('%H:%M')}. EOD in {time_till_bed.seconds // 3600}:{(time_till_bed.seconds // 60) % 60} (at {BED_TIME.strftime('%H:%M')}).",
            "-contentImage", "https://i.pinimg.com/originals/fc/60/62/fc60622ac3c047ba90d9adaba24325bd.jpg"])
    time.sleep(10)
