#!/usr/bin/env python3

import time
import os
import subprocess
from datetime import datetime as dt, timedelta

EVERY = 2

def bedtime():
    return dt.now().replace(hour=21, minute=0, second=0, microsecond=0)

hour = 0
while hour <= dt.now().hour - EVERY:
    hour += EVERY

BED_TIME = bedtime() 
while True:
    time.sleep(1)
    if hour >= 24:
        BED_TIME = bedtime() 
        hour = 0
    print(hour, dt.now().hour)
    if hour <= dt.now().hour:
        hour += EVERY
        name = os.path.basename(__file__)
        time_till_bed = BED_TIME - dt.now()
        subprocess.run(["terminal-notifier", 
            "-title", "Reflect now", 
            "-message", f"It's {dt.now().strftime('%H:%M')}. EOD in {time_till_bed.seconds // 3600}:{(time_till_bed.seconds // 60) % 60 + 1} (at {BED_TIME.strftime('%H:%M')}).",
            "-contentImage", "https://i.pinimg.com/originals/fc/60/62/fc60622ac3c047ba90d9adaba24325bd.jpg"])
