#!/usr/bin/fish

ffmpeg -i file:$argv[1] -filter_complex "drawtext=fontfile=/usr/share/fonts/truetype/noto/NotoSansMono-Regular.ttf: text='%{eif\:n/2/60/60\:d\:2}\:%{eif\:mod(n/2/60, 60)\:d\:2}\:%{eif\:mod(n/2,60)\:d\:2}': x=0 : y=0 : box=1" -c:a copy out.mp4
