#!/usr/bin/fish

argparse -X 0 'w/whiter' 'r/redder' 'b/brighter' 'd/darker' -- $argv 
or exit 1

set redness_step 400
set brightness_step 0.1

set config $HOME/.redshift-mem

touch $config
set vars (cat $config)

set brightness $vars[1]
set redness $vars[2]

if set -q brightness
  set brightness 1
end
if set -q redness
  set redness 5000
end

if set -q _flag_w
  echo hello
  set redness (math "$redness + $redness_step")
end
if set -q _flag_r
  set redness (math "$redness - $redness_step")
end
if set -q _flag_b
  set brightness (math "$brightness + $brightness_step")
end
if set -q _flag_d
  set brightness (math "$brightness - $brightness_step")
end

echo -e "$brightness\n$redness" > $config
cat $config

#redshift -O 1500 -b 0.2
