#!/usr/bin/fish

set locks_dir $HOME/locks

if not [ -d $locks_dir ]
    echo "creating locks dir: $locks_dir"
    mkdir $locks_dir
end

function lock
    set lock_name $argv[1]
    touch "$locks_dir/$lock_name"
end

function unlock
    set lock_name $argv[1]
    rm "$locks_dir/$lock_name"
end

function check
    set lock_name $argv[1]
    if [ $lock_name = "ANY" ]
        set lock_files (ls $locks_dir)
        if [ -z "$lock_files" ] 
            exit 0 
        else
            exit 1
        end
    end

    if [ -f "$locks_dir/$lock_name" ]
        exit 1
    else 
        exit 0
    end
end

function show
    ls $locks_dir
end

$argv[1] $argv[2..]
