#!/usr/bin/fish
set pid_path "/tmp/gsay-clip.pid"

if [ -f "$pid_path" ]
    kill -SIGTERM (cat $pid_path)
    rm "$pid_path"
    exit 0
end

set text (xclip -selection primary -out)
gsay --speed 1.4 "$text" &
echo $last_pid > "$pid_path"
wait
rm "$pid_path"
