#!/usr/bin/env fish

set script_name (basename (status --current-filename))
set state_file "$HOME/$script_name"".state"
set c 0

if [ -f "$state_file" ]
    set c (cat "$state_file")
end

switch $c
case 0
    setxkbmap -layout us -variant dvp
case 1
    setxkbmap -layout us
case 2
    setxkbmap -layout de
end

echo (math "($c+1)%3") > "$state_file"

exit 0
