#!/usr/bin/fish

echo -n (setxkbmap -query | grep layout | string replace -r 'layout:' '' | string trim)
set var (setxkbmap -query | grep variant | string replace -r 'variant:' '' | string trim)

if [ "$var" != "" ]
    echo -n "/"
end

echo $var
