#!/usr/bin/fish

set delay 3

switch $argv[1]
  case f1
    trap "irsend SEND_STOP presberg_room1_light KEY_F1; exit 2" SIGINT
    irsend SEND_START presberg_room1_light KEY_F1
    sleep $delay
    irsend SEND_STOP presberg_room1_light KEY_F1
  case f2
    trap "irsend SEND_STOP presberg_room1_light KEY_F2; exit 2" SIGINT
    irsend SEND_START presberg_room1_light KEY_F2
    sleep $delay
    irsend SEND_STOP presberg_room1_light KEY_F2
  case f3
    trap "irsend SEND_STOP presberg_room1_light KEY_F3; exit 2" SIGINT
    irsend SEND_START presberg_room1_light KEY_F3
    sleep $delay
    irsend SEND_STOP presberg_room1_light KEY_F3
  case onoff
    trap "irsend SEND_STOP presberg_room1_light KEY_POWER; exit 2" SIGINT
    irsend SEND_START presberg_room1_light KEY_POWER
    sleep $delay
    irsend SEND_STOP presberg_room1_light KEY_POWER 
  case reset
    irsend SEND_STOP presberg_room1_light KEY_POWER 
    irsend SEND_STOP presberg_room1_light KEY_F3
    irsend SEND_STOP presberg_room1_light KEY_F2
    irsend SEND_STOP presberg_room1_light KEY_F1
end

exit 0
