#!/usr/bin/fish

function rnds
    set -l mdir $HOME/music/vocaloid_mp3
    set -l a (ls $mdir | sort -R)[1]
    echo $mdir/$a
end


set short false
switch $argv[1]
    case short
        set short true
    case '*'
        echo "Invalid arg"
        exit 1
end



echo $short NOT WORKING

alarm-timer -m 22; 
if $short
    mpv (rnds)
    lightctl f1
else
    mpv (rnds) --end 10
end

alarm-timer -h 1
lightctl f1

alarm-timer -m 8 --em "" --im ""
mpv (rnds)

while true
    read -p "echo send SIGINT to exit"
end
