#!/usr/bin/fish

function rnds
    set -l mdir $HOME/music/vocaloid_mp3
    set -l a (ls $mdir | sort -R)[1]
    echo $mdir/$a
end

set short false
set no_recording false
if [ -n "$argv[1]" ]
    switch $argv[1]
        case --short
            set short true
        case --no-recording
            set no_recording true
        case '*'
            echo "Invalid arg"
            exit 1
    end
end

if eval $no_recording
    espeak "no recording"
else
    espeak "start recording"
    raspivid -o ~/capture/(date -Is)_lucid.avi -w 640 -h 480 -fps 2 -b 40000 -t 0 &
end

alarm-timer -m 22; 
if eval $short
    mpv (rnds)
    lightctl f1
else
    mpv (rnds) --end 10
end

alarm-timer -h 1
lightctl f1

alarm-timer -m 8 --em "" --im ""
mpv (rnds)

while true
    read -p "echo send SIGINT to exit"
end
