#!/usr/bin/fish

set name (basename (status --current-filename))

function help
    echo "usage:"
    echo "  $name --pi2me"
    echo "  $name --me2pi"
end

if [ (count $argv) -gt 2 ]
    help
    exit 1
end

if [ $argv[1] = "--pi2me" ]
    for i in bed_notes_pi.org dream_journal_pi.org
      rsync -a pi@(getip pi):Documents/"$i" $HOME/data/org/pi-file_buffer/
    end
else if [ $argv[1] = "--me2pi" ]
    for i in bed_notes_pi.org dream_journal_pi.org
      rsync -a $HOME/data/org/pi-file_buffer/"$i" pi@(getip pi):Documents/
    end
else
    help
end
