#!/usr/bin/fish

set DEFAULT_FILE "/home/johannes/data/rip/youtube/STUDY WITH MIKU - part1 - [gdssxLx7ofs].webm"
set DEFAULT_CAMERA "/dev/video2"

argparse 'h/help' 'f/file=' 'c/camera=' -- $argv

function help
    echo '-h --help        Show this message.' 
    echo '-f --file FILE   The background file to play.' 
    echo '-c --camera FILE The camera device file, to put into the background.'
end

if set -q _flag_help
    help
    exit 0
end

if not set -q _flag_file
    set _flag_file "$DEFAULT_FILE"
end
if not set -q _flag_camera
    set _flag_camera "$DEFAULT_CAMERA"
end

mpv --really-quiet "$_flag_file" --external-file="$_flag_camera" --lavfi-complex="[vid2] scale=1920x1080,crop=1080:1080,pad=iw+4:ih+4:2:2:color=black@0,perspective=661:400:685:322:709:573:720:453:sense=1,limiter=10:200 [vid3]; [vid1][vid3] overlay [vo]" &
disown
