#!/usr/bin/env bash

loud_volume=70%

tulpa () {
    echo "Tulpa training"
    [ $NO_HIGH_VOLUME ] || set_volume $loud_volume

    if [ $SHORT ]; then
        t=5;
        toggl start -o tulpa_training
        alarm-timer -m $t --im "$t minute tulpa training"
    else
        t=5;
        toggl start -o tulpa_training
        alarm-timer -m $t --im "$t minutes talking out loud"
        alarm-timer -m $t --im "$t minutes with caitlyn and Vanders"
        alarm-timer -m $t --im "$t minute adventure"
    fi
    reset_vol
}

prophantasia () {
    echo "Prophantasia training"
    [ $NO_HIGH_VOLUME ] || set_volume $loud_volume
    toggl start -o imposition_training

    if [ $SHORT ]; then
        t=5
        alarm-timer -m $t --im "$t minutes prophantasia"
    else
        t=5
        alarm-timer -m $t --im "$t minutes image streaming"
        alarm-timer -m $t --im "$t minutes prophantasia"
    fi
    reset_vol
}

premeditation () {
        start_delay=20
        toggl start -o 瞑想
        alarm-timer --im "starting meditation in $start_delay seconds" --em "" $start_delay
        alarm-timer 1 --im "$t minute meditation" --em ""
        alarm-timer -m $t
}

meditation () {
    echo "Meditation"
    start_delay=20
    set_volume 32%
    toggl start -o 瞑想
    alarm-timer --im "starting meditation in $start_delay seconds" --em "" $start_delay

    if [ $SHORT ]; then
        t=12
        alarm-timer --im "$t minute meditation" --em "" 1
        autoclicker 1 0 1
        alarm-timer -m $t --im ""
    else
        t=20
        alarm-timer --im "$t minute daily meditation" --em "" 1
        autoclicker 1 0 1
        alarm-timer -m $t --im ""

        #t=20
        #alarm-timer --im "$t minute free meditation. Setup now." --em "" 1
        #alarm-timer -m $t --im ""
    fi
    reset_vol
}

# ==================

set_volume () {
    new_volume=$1
    orig_vol=$(get-volume)
    pactl set-sink-volume alsa_output.pci-0000_0a_00.4.analog-stereo $new_volume
}

reset_vol () {
    pactl set-sink-volume alsa_output.pci-0000_0a_00.4.analog-stereo $orig_vol
}

trap reset_vol INT
trap reset_vol EXIT

# ===================

if ! args=$(getopt --name $(basename $0) \
        -o hvstmp \
        --longoptions help,no-high-volume,short,tulpa,meditation,prophantasia,premeditation \
        -- "$@"); then
     exit 1
fi

for arg in $args; do
    case "$arg" in
        -v | --no-high-volume)
            echo "Avoiding use of high volumes"
            NO_HIGH_VOLUME=true
            ;;
        -s | --short)
            echo "Using short activity versions"
            SHORT=true
            ;;
        -h | --help)
            echo '-t | --tulpa)            Tulpa training.'
            echo '-p | --prophantasia)     Prophantasia training.'
            echo '-m | --meditation)       Start a Meditation.'
            echo '--premeditation)         Start a short Meditation.'
            echo '-v | --no-high-volume)   Do not change volume before starting for high volumes.'
            echo '-s | --short)            Do the short version of the activities.'
            echo '-h | --help)             Show this message.'
            exit 0
            ;;
    esac
done

for arg in $args; do
    case "$arg" in
        -t | --tulpa)
            tulpa
            ;;
        -m | --meditation)
            meditation
            ;;
        --premeditation)
            premeditation
            ;;
        -p | --prophantasia)
            prophantasia
            ;;
    esac
done
