#!/bin/bash

loud_volume=80%

tulpa () {
    echo "Tulpa training"
    [ NO_HIGH_VOLUME ] || set_volume $loud_volume

    if [ $SHORT ]; then
        toggl start -o tulpa_training
        alarm-timer -m 5 --im "5 mitute tulpa training"
    else
        toggl start -o 瞑想
        alarm-timer -m 5
        toggl start -o tulpa_training
        alarm-timer -m 5 --im "talk out loud"
        alarm-timer -m 5 --im "caitlyn"
        alarm-timer -m 5 --im "adventure"
    fi
}

prophantasia () {
    echo "Prophantasia training"
    [ NO_HIGH_VOLUME ] || set_volume $loud_volume
    toggl start -o imposition_training

    if [ $SHORT ]; then
        alarm-timer -m 5 --im ""
    else
        alarm-timer -m 10 --im prophantasia
    fi
}

meditation () {
    echo "Meditation"
    start_delay=20
    set_volume 32%
    toggl start -o 瞑想
    alarm-timer --im "starting meditation in $start_delay seconds" --em "" $start_delay
    autoclicker 1 0 1

    if [ $SHORT ]; then
        alarm-timer -m 12 --im ""
    else
        alarm-timer -m 25 --im ""
    fi
}

# ==================

set_volume () {
    volume=$1
    reset_vol () {
        pactl set-sink-volume alsa_output.pci-0000_0a_00.4.analog-stereo $orig_vol
        exit 0
    }

    orig_vol=$(get-volume)

    trap reset_vol INT
    trap reset_vol EXIT

    pactl set-sink-volume alsa_output.pci-0000_0a_00.4.analog-stereo $volume
}

# ===================

if ! args=$(getopt --name $(basename $0) \
        -o hvstmp \
        --longoptions help,no-high-volume,short,tulpa,meditation,prophantasia \
        -- "$@"); then
     exit 1
fi

for arg in $args; do
    case "$arg" in
        -v | --no-high-volume)
            echo "Avoiding use of high volumes"
            NO_HIGH_VOLUME=true
            ;;
        -s | --short)
            echo "Using short activity versions"
            SHORT=true
            ;;
        -h | --help)
            echo '-t | --tulpa)            Tulpa training.'
            echo '-p | --prophantasia)     Prophantasia training.'
            echo '-m | --meditation)       Start a Meditation.'
            echo '-v | --no-high-volume)   Do not change volume before starting for high volumes.'
            echo '-s | --short)            Do the short version of the activities.'
            echo '-h | --help)             Show this message.'
            exit 0
            ;;
    esac
done

for arg in $args; do
    case "$arg" in
        -t | --tulpa)
            tulpa
            ;;
        -m | --meditation)
            meditation
            ;;
        -p | --prophantasia)
            prophantasia
            ;;
    esac
done

