#!/usr/bin/env bash
# This is a simple terminal alarm clock

help_message () {
  echo "usage: $(basename $0) [OPTIONS] secondsToAlarm [OPTIONS]"
  echo "       Arguments to long options are also requried for short options."
  echo ""
  echo "Options:"
  echo "  -w, --wait: Dont terminate timer but wait and repeat the message"
  echo "              after the time runs out."
  echo "  --em MESSAGE: The message to say when time is up."
  echo "                 default=\"$message\""
  echo "  --im MESSAGE: The message to say when starting the timer."
  echo "                 default=\"$imessage\""
  echo "  -s, --seconds: Seconds to alarm. Can be used as alternative"
  echo "                 to passing the seconds as an argument."
  echo "  -m, --minutes: Minutes to alarm."
  echo "  -h, --hours: Hours to alarm."
  echo "  -t, --text: Text to show before timer."
  echo "  -r, --repeat: Restart timer when time runs out."
  echo "  -e, --espeakargs: The args to pass to espeak (or say if espeak"
  echo "                    is not found) as one string."
  echo "  -v, --verbose: Enable additional output."
  echo "  --help: Display this message."
}

if [ $(uname) = "Darwin" ]; then
    date_cmd=gdate
else
    date_cmd=date
fi

# Default arguments
message="Your time is up!"
imessage="Go"
prompt=""

espeakargs=""

speed=175
pitch=50

seconds=0
minutes=0
hours=0

repeat=false
verbose=false
warn=false

# Parse the arguments
while test $# -gt 0
do
  case "$1" in
    --help) help_message; exit 0
      ;;
    -w|--wait) wait_on_exit=true
      ;;
    --em) message=$2; shift
      ;;
    --im) imessage=$2; shift
      ;;
    -S|--silent) message=""; imessage=""
      ;;
    -H|--hide-timer) hide_timer=true
      ;;
    -s|--seconds) seconds=$2; shift
      ;;
    -m|--minutes) minutes=$2; shift
      ;;
    -h|--hours) hours=$2; shift
      ;;
    -e|--espeakargs) espeakargs=$2; shift
      ;;
    -v|--verbose) verbose=true
      ;;
    -t|--text) text="$2"": "; shift
      ;;
    -r|--repeat) repeat=true
      ;;
    --warn) warn=true
      ;;
    -*) echo "Bad option $1"; exit 1
      ;;
     *) seconds="$1"
      ;;
  esac
  shift
done

if [ "$seconds" == 0 ] && [ "$minutes" == 0 ] && [ "$hours" == 0 ]; then
  help_message
  exit 1
fi

if which gsay > /dev/null; then
  function speak_cmd {
    "gsay" $1
  }
elif [ -n $(command -v say) ]; then
  function speak_cmd {
    "say" $1
  }
elif [ -n $(command -v espeak) ]; then
  function speak_cmd {
      o_vol=$(echo $(pulsemixer --get-volume) | cut -d" " -f1)
      amixer -c 1 set 'Auto-Mute Mode' Disabled > /dev/null
      # pactl -- set-sink-volume 0 50%
      espeak "$1"
      # pactl -- set-sink-volume 0 "$o_vol"%
      amixer -c 1 set 'Auto-Mute Mode' Enabled > /dev/null
   }
else
  echo "No tts command found"
  exit 1
fi

START_TIME=$($date_cmd '+%s')
END_TIME=$($date_cmd '+%s' -d "+ $hours hours + $minutes minutes + $seconds seconds")
READABLE_END_TIME=$($date_cmd -d "+ $hours hours + $minutes minutes + $seconds seconds")
# echo "End time: $READABLE_END_TIME"

sec=$((END_TIME - $($date_cmd '+%s')))
while true; do
  speak_cmd "$imessage"
  sec_remaining=sec
  while true; do
      sec_remaining="$(($sec_remaining-1))"
      if [ ! "$hide_timer" ]; then
          echo -ne "\r\033[K"$text$((sec_remaining / (60 * 60)))h $(((sec_remaining / 60) % 60))m $((sec_remaining % 60))s
      fi
      [[ "$sec_remaining" -le 0 ]] && break
      if $warn; then
        for t in 30 60 120 240 600 900 1800; do
          if [ t = 30 -o t = 60 ]; then
            speak_cmd "$t seconds remaining"
            break
          fi
          [[ "$sec_remaining" == $t ]] && speak_cmd "$((t / 60)) minutes remaining"
        done
      fi
      ans=""
      if read -n1 -t1 -s ans; then
        printf " <> pause"
        while [ ! -z $(read -n1 -s ans) ]; do
          :
        done
        echo -ne "\r\033[K"
      fi
  done

  speak_cmd "$message"

  if [ ! -z "$wait_on_exit" ]; then
    echo -e "\nPlease terminate $(basename $0), pid $$"
    while true; do
      sleep 4
      speak_cmd "$message"
    done
  fi

  if ! $repeat; then
    break
  fi
done

echo ""

exit 0
