#!/bin/bash

if ! [ -z "$1" ]; then
    org_path="$1"
else
    # Aqua backwards compatability
    org_path="$HOME/data/org"
fi

if ! [ -z "$2" ]; then
    ping_url="$2"
else
    # Aqua backwards compatability
    ping_url='https://hc-ping.com/ce8169be-85e0-4e22-b574-c35f45ae3302'
fi

ping () {
    val="$1"
    if ! [ -z $val ]; then
        val="/$val"
    fi
    curl --retry 3 "$ping_url""$val"
}

backup-org () {
    cd $org_path || return 1
    git add . || return 1
    git commit -m "cron-auto-commit$(date -Im)" || return 1
    git pull origin master || return 1
    git push origin master || return 1
}

ping start

if ( cd $org_path && git diff-index --quiet HEAD ); then
    ping
    exit 0
fi

if ! backup-org; then
    ping 1
else
    ping
fi
