#!/bin/bash

if [ $(hostname) = "rimuru" ]; then
    org_path="$HOME/org"
    ping_url='https://hc-ping.com/0a33c73d-49f0-4db4-b31f-5d2ae0f2b842'
elif [ $(hostname) = "Aqua" ]; then
    org_path="$HOME/data/org"
    ping_url='https://hc-ping.com/ce8169be-85e0-4e22-b574-c35f45ae3302'
else
    echo "unknown computer"
    exit 1
fi

ping () {
    val="$1"
    if ! [ -z $val ]; then
        val="/$val"
    fi
    curl --retry 3 "$ping_url""$val"
}

backup-org () {
    echo chdir
    cd $org_path || return 1
    echo add
    git add . || return 1
    echo comm
    git commit -m "cron-auto-commit$(date -Im)" || return 1
    echo pull
    git pull origin master || return 1
    echo push
    git push origin master || return 1
}

ping start

if ( cd $org_path && git diff-index --quiet HEAD ); then
    echo no changes, no commiting neccesary
    ping
    exit 0
fi

if ! backup-org; then
    echo error in backup-org
    ping 1
else
    echo backup complete
    ping
fi
