#!/bin/bash
source ~/anaconda3/etc/profile.d/conda.sh
conda activate deepspeech

Tailor_paths="$HOME/TAIlor $HOME/data/projects/misc/Tailor"
for p in $Tailor_paths; do
    if [[ -d "$p" ]]; then
        Tailor_path="$p"
        break
    fi
done

if [[ -z "$Tailor_path" ]]; then
    echo $Tailor_path
    echo "tailor path not found. Searched in ""$Tailor_paths"
    exit 1
fi

if [[ -z $1 ]]; then
    fname="$Tailor_path"/deepspeech-0.6.1-models/audio/"$(date -Is)".wav
    echo "writing to audiofile $fname"
    ffmpeg -f alsa -i default "$fname"
else
    echo nono
    fname=$1
fi

model_path=$Tailor_path/deepspeech-0.6.1-models/deepspeech-0.6.1-models/output_graph.pbmm

deepspeech --model "$model_path" --audio "$fname"

mplayer "$fname"

exit 0
