#!/bin/sh
# Note that you only get the right audio channel volume. The left one would be $5. 
vol=$(pactl get-sink-volume $(pactl get-default-sink) | awk '/Volume:/ {print $12}')
mute=$(pactl get-sink-mute $(pactl get-default-sink) | awk '{print "m:"$2}')
echo $mute $vol
