#!/bin/sh
getdefaultsinkname() {
    pacmd stat | awk -F": " '/^Default sink name: /{print $2}'
}

getdefaultsinkvol() {
    pacmd list-sinks |
        awk '/^\s+name: /{indefault = $2 == "<'$(getdefaultsinkname)'>"}
            /^\s+volume: / && indefault {print $5; exit}'

}

get_main_sink_vol() {
    pacmd list-sinks |
        awk '/^\s+name: /{indefault = $2 == "<alsa_output.pci-0000_0a_00.4.analog-stereo>"}
            /^\s+volume: / && indefault {print $5; exit}'

}

setdefaulsinkvol() {
    pactl set-sink-volume $(getdefaultsinkname) $1
}

echo $(get_main_sink_vol) #ms:$(pactl list sinks | grep mic_mix_sink-their_mixer -C 4 | grep Mute: | sed 's/\sMute\:\s//g')
