#!/bin/bash

espeak "go"
i=0

music1=$HOME/music/*Netgame*

init_wait=15
debug=false

espeak "lucid-script start."
espeak "block one starts in $init_wait minutes"
if ! $debug; then
  sleep "$init_mait"m
fi

while true; do
  if [ $i -gt 0 ]; then
    espeak "block $i over. $((i*90/60)) hours. $(((i*90)%60)) minutes." -s 130 -a 50
    if ! $debug; then
      espeak "are you sleeping" -a 50
      sleep 1
      espeak "Are you sleeping?" -s 150 -a 50
      sleep 3
      espeak "Are you sleeping?" -s 100 -a 50

    fi
  fi
  if [ $i = 4 ]; then
    mpv --vo=null $music1 -ss 0 --end 11.5 --volume 50
  fi

  if [ $i -ge 7 ]; then
    mpv --vo=null $music1 -ss 0 --end 11.5 --volume 80
  fi

  if [ $i -ge 6 ]; then
    espeak "Wake up"
  fi

  if [ $i -ge 7 ]; then
    for i in $(seq 10); do
      espeak "Wake up"
    done
  fi

  if ! $debug; then
    alarm-timer -m 80 --im "" --em ""
  fi

  i=$(($i + 1))
done
