#!/bin/bash

# This program organises a routine of pre sleep activities to facilitate lucid dreaming
# and tries to wake you up between sleep cycles so that you can try to go back to sleep
# while applying a lucid dreaming technique. It also serves as a wakeup alarm clock.

music1=$HOME/music/*Netgame*
music_wakeup=$HOME/music/*
rand_song=$(echo $HOME/music/vocaloid | shuf)[0]
echo $rand_song
meditation_time=5
init_wait=15

function alarm-timer {
    if $no_timer; then
        echo "skipping timer"
    else
        command alarm-timer --im "" --em "" "$@"
    fi
}

function espeak {
    echo "$@"
    if ! $no_voice; then
        command espeak -a 50 "$@"
    fi
}

no_timer=false
no_voice=false
while [ $# -gt 0 ]; do
    case $1 in
        --no-timer)
            no_timer=true
            shift
            ;;
	--no-voice)
            no_voice=true
	    shift
	    ;;
        *)
            echo "invalid arg $1"
            exit 1
            ;;
    esac
done

espeak "start"

espeak "$meditation_time minute meditation starts in 10 seconds"
alarm-timer 10
espeak "go"
alarm-timer -m 5
espeak "meditation complete"

espeak "1 minute lucid mantra"
alarm-timer -m 1

espeak "Do reality check"
alarm-timer 5

espeak "block one starts in $init_wait minutes"
alarm-timer -m "$init_wait"

i=0
while true; do
    if [ $i -ge 6 ]; then
        m="block $i over. $((i*90/60)) hours. $(((i*90)%60)) minutes."
        espeak "$m" -s 130
    fi

    if [ $i -ge 6 ]; then
        alarm-timer 0 --im "lucid wake. stand up." --em ""
        alarm-timer 10 --im "lucid wake. stand up." --em ""
        mpv --vo=null $music1 --volume 45 #--end 11.5
        espeak "lay down"
    fi

#    if [ $i -ge 2 -a $i -le 3 -o $i -eq 5  ]; then
#        mpv --vo=null $music1 --end 11.5 --volume 50
#	espeak "Are you sleeping"
#        alarm-timer 1 --im "" --em ""
#        espeak "Are you sleeping?" -s 150
#        alarm-timer 2 --im "" --em ""
#        espeak "Are you sleeping?" -s 100
#    fi
#
#    if [ $i -eq 4 ]; then
#        for _ in $(seq 6); do
#    	alarm-timer 10 --im "lucid wake. stand up." --em ""
#        done
#        espeak "lay down"
#        alarm-timer 10 --im "" --em ""
#        espeak "lay down"
#    fi

    if [ $i -ge 7 ]; then
        mpv $music_wakeup --vo=null --shuffle --volume 55
        mpv $music_wakeup --vo=null --shuffle --volume 70
        mpv $music_wakeup --vo=null --shuffle --volume 100
    fi

    alarm-timer -m 90
    i=$(($i + 1))
done
