#!/usr/bin/env bash

log_file="/home/johannes/resume_test_err_2.txt"

echo $(date) start > "$log_file"

{

if [ $(hostname) = Rimuru ]; then
  export DISPLAY=:1
fi

# Displays
if [ $(hostname) = Aqua ]; then
  xrandr --auto
  xrandr --output DVI-D-0 --primary
  xrandr --output HDMI-0 --right-of DVI-D-0
  xrandr --output DP-2 --right-of HDMI-0
  xset dpms $((60 * 10)) $((60 * 30)) $((60 * 45))
fi

# Keyboard
xset s off
xset r rate 250 30
setxkbmap -option compose:ralt
setxkbmap -layout us -variant dvorak

# Touchpad
xinput --set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Tapping Enabled' 1
xinput --set-prop 'SynPS/2 Synaptics TouchPad' 'libinput Natural Scrolling Enabled' 1


## Map capslock to escape
setxkbmap -option caps:escape

# Misc
if [ $(hostname) = Aqua ]; then
  hsetroot -solid '#09000F'
  nitrogen --restore
  wacom-setup inkscape
fi

} >> "$log_file" 2>> "$log_file"
