#!/bin/bash

file_name=$1

if [ -z "$file_name" ]; then
    echo ERROR first argument needs to be the file name
    exit 1
fi

inkscape=inkscape-b

path=/mnt/data_main/org/main/svgs
template=$path/org_template.svg

path_svg=$path/$file_name.svg
path_png=$path/$file_name.png

if [ -f "$path_svg" ]; then
    echo "file name exsists, opening exsisting"
else
    echo "creating $path_svg"
    cp $template $path_svg
fi

echo "opening $path_svg"
$inkscape $path_svg

echo "exporting to png"
$inkscape --export-area-drawing -o $path_png $path_svg

echo "[[$path/$file_name.png]]" | xclip
echo "[[$path/$file_name.png]]" | xclip -selection c
echo "png path copied to both clipboards"
