#!/bin/bash

device="alsa_output.pci-0000_09_00.4.analog-stereo.monitor"
name="/home/johannes/data/capture/audio/"$(date -Is)"_$1".mp3
echo "captureing:      $device"
echo "saving to file:  $name"
parec -d "$device" | lame -r -V0 - "$name"
