#!/bin/bash

if [ -z "$1" ]; then
    echo specify the computer name as first argument
    exit 1
fi

name="$1"

# cd "$HOME"
# 
# mkdir ~/bin
# 
# # get root
# sudo echo got root
# 
# echo generate and install ssh key
# ssh-keygen -f ~/.ssh/"$name"_rsa
# ssh-copy-id -i .ssh/"$name"_rsa batou.ddns.net
# 
# echo conda install
# cd Downloads
# wget 'https://repo.anaconda.com/miniconda/Miniconda3-py39_4.12.0-Linux-x86_64.sh' || exit 1
# sh 'Miniconda3-py39_4.12.0-Linux-x86_64.sh' || exit 1 
# conda config --set auto_activate_base false
# cd
#
# Setup
#git config --global user.name "Johannes C. Mayer"
#johannes@pop-os:~/suspend-hack$ git config --global user.email "j.c.mayer240@gmail.com"
#
# echo install my programs
# mkdir ~/software_projects
# git clone git@github.com:johannesCmayer/shell-fish-legs.git ~/software_projects/shell-fish-legs  || exit 1
# cd bin || exit 1
# ln -s ~/software_projects/shell-fish-legs shell || exit 1
# ln -s shell/bash/alarm-timer || exit 1
# ln -s shell/bash/stopwatch || exit 1
# ln -s shell/bash/cron-git-backup || exit 1
# ln -s shell/bash/toggle-touchpad || exit 1
# ln -s shell/fish/wacom-setup || exit 1
# cd

#echo copy my data
#git clone git@github.com:johannesCmayer/org.git org || exit 1

#echo copy config
#git clone git@github.com:johannesCmayer/.config.git /tmp/.config || exit 1
#rsync -a /tmp/.config/ ~/.config
#ln -s .config/spacemacs .spacemacs || exit 1
#ln -s .config/emacs.d .emacs.d || exit 1
#
#echo copy secrets
#mkdir ~/.ssh
#rsync -a batou.ddns.net:.ssh/ ~/.ssh || exit 1
#mkdir ~/.gnupg
#rsync -a batou.ddns.net:.gnupg/ ~/.gnupg || exit 1
#mkdir ~/.password-store
#rsync -a batou.ddns.net:.password-store/ ~/.password-store || exit 1

echo misc install
sudo apt install -y htop qtqr nemo zathura gnome-tweaks || exit 1
sudo apt install -y python3 python-is-python3 python3-pip ipython3 
pip install yt-dlp jupyterlab || exit 1
flatpak install -y flathub com.discordapp.Discord  || exit 1
flatpak install -y flathub com.slack.Slack || exit 1
flatpak install -y flathub com.brave.Browser || exit 1

echo Install fish
sudo apt-add-repository -y ppa:fish-shell/release-3
sudo apt update
sudo apt install fish -y || exit 1

echo neovim
sudo apt install neovim -y || exit 1

echo Install Cuda
sudo apt install system76-cuda-latest system76-cudnn-11.2 -y || exit 1

echo configure compose key + CAPS is ESC
echo configure autostart applications
echo configure cron-git-backup
echo configure key-repeat speed
echo configure suspending
echo configure descop background
echo configure tilebars
echo install alacritty, timeshift
echo setup brave, account logins

echo REBOOT REQUIRED

