#!/bin/bash

last_path="$HOME"/last_desktop.txt
current_path="$HOME"/current_desktop.txt

last=$(cat "$last_path")
current=$(cat "$current_path")
new=$1

if [ $1 = "last" ]; then
    wmctrl -s $last
    echo $current > "$last_path"
    echo $last > "$current_path"
elif [  $1 = "current" ]; then
    wmctrl -s $current
else
    wmctrl -s $new
    if [ $new != $current ]; then
        echo $current > "$last_path"
        echo $new > "$current_path"
    fi
fi
