#!/bin/bash

# Restart pipewire
systemctl --user restart pipewire.service
systemctl --user restart pipewire-pulse.service

# Create virtual devices
pactl load-module module-null-sink media.class=Audio/Sink sink_name=my-combined-sink channel_map=stereo
pactl load-module module-null-sink media.class=Audio/Source/Virtual sink_name=my-virtualmic channel_map=front-left,front-right

sleep 5

# Link Desktop audio
## Link Akira monitor
pw-link bluez_output.60_AB_D2_41_8E_E6.1:monitor_FL my-combined-sink:playback_FL
pw-link bluez_output.60_AB_D2_41_8E_E6.1:monitor_FR my-combined-sink:playback_FR
## Link integrated speakers monitor
pw-link alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink:monitor_FL my-combined-sink:playback_FL
pw-link alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink:monitor_FR my-combined-sink:playback_FR

# Link microphones
## Link Akira mic
pw-link bluez_input.60_AB_D2_41_8E_E6.0:capture_MONO my-combined-sink:playback_FL
pw-link bluez_input.60_AB_D2_41_8E_E6.0:capture_MONO my-combined-sink:playback_FR
## Link integrated mic
pw-link alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_6__source:capture_FL my-combined-sink:playback_FL
pw-link alsa_input.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp_6__source:capture_FR my-combined-sink:playback_FR

# Link virtual sink to virtual mic
pw-link my-combined-sink:monitor_FL my-virtualmic:input_FL
pw-link my-combined-sink:monitor_FR my-virtualmic:input_FR
